"""initial migration"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d93ba18c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False, default=False),  # Cambiado a nullable=False y añadido default=False
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Pais',  # Cambiado el nombre de la tabla a 'Pais'
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais'], ['Pais.id'], ),  # Cambiado a 'Pais.id'
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Localidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia'], ['Provincia.id'], ),  # Cambiado a 'Provincia.id'
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('localidad', sa.Integer(), nullable=False),
    sa.Column('domicilio', sa.String(length=100), nullable=False),
    sa.Column('f_nacimiento', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, default=True),  # Cambiado a nullable=False y añadido default=True
    sa.ForeignKeyConstraint(['localidad'], ['Localidad.id'], ),  # Cambiado a 'Localidad.id'
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Persona')
    op.drop_table('Localidad')
    op.drop_table('Provincia')
    op.drop_table('Pais')
    op.drop_table('User')
    # ### end Alembic commands ###
